version: "3.8"

services:
  node:
    image: anyaloza/task7-pis:latest
    build: .
    depends_on:
      - pgsql
    container_name: task7-pis
    environment:
      - DB_HOST=pgsql
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=db-pis
    ports:
      - "3000:3000"
    user: root
    restart: on-failure
    deploy:
      replicas: 4
      restart_policy:
        condition: on-failure

  pgsql:
    container_name: postgres
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 2s
      timeout: 10s
      retries: 5
    restart: always
